-- Expand the public, source-backed research registry across the next set of
-- headline conjectures. These rows describe prior work and replay entry
-- points; they are not Agent checkpoints, Lean receipts, or proof claims.
INSERT OR IGNORE INTO `curated_research_records` (
	`id`, `problem_revision_id`, `role`, `kind`, `title`, `authors`, `summary`,
	`source_system`, `source_url`, `source_identifier`, `occurred_at`,
	`curation_status`, `lean_repository_url`, `lean_commit`, `lean_declaration`, `position`
) VALUES
(
	'curated:goldbach:helfgott-major-arcs',
	'problem-revision:formal-conjectures:goldbach:main:1',
	'key_lemma',
	'paper',
	'Major arcs for Goldbach''s problem',
	'Harald A. Helfgott',
	'This paper supplies a major-arc component in the analytic treatment of the ternary Goldbach problem. It is a predecessor result for the binary target, not a proof of the binary Goldbach conjecture.',
	'arXiv',
	'https://arxiv.org/abs/1305.2897',
	'arxiv:1305.2897',
	'2013-05-13',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:goldbach:computational-verification',
	'problem-revision:formal-conjectures:goldbach:main:1',
	'progress',
	'paper',
	'Empirical verification of the even Goldbach conjecture and computation of prime gaps up to 4 x 10^18',
	'Tomás Oliveira e Silva; Siegfried Herzog; Silvio Pardi',
	'Computational verification covers every even number up to 4 x 10^18. The finite check is valuable reproducibility context, but it does not settle all even integers.',
	'American Mathematical Society',
	'https://doi.org/10.1090/S0025-5718-2013-02787-1',
	'doi:10.1090/S0025-5718-2013-02787-1',
	'2013-11-18',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	20
),
(
	'curated:goldbach:formal-conjectures-target',
	'problem-revision:formal-conjectures:goldbach:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the exact binary Goldbach declaration and source hash for a local Lean replay. The declaration is admitted in the catalog and is not itself a proof.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/GoldbachConjecture.lean#L33-L34',
	'github:google-deepmind/formal-conjectures:goldbach',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'GoldbachConjecture.goldbach',
	30
),
(
	'curated:collatz:tao-almost-all',
	'problem-revision:formal-conjectures:collatz:main:1',
	'progress',
	'paper',
	'Almost all orbits of the Collatz map attain almost bounded values',
	'Terence Tao',
	'Tao proves an almost-all logarithmic-density result for Collatz orbits. It is a major partial result, but it does not prove that every positive integer reaches 1.',
	'arXiv',
	'https://arxiv.org/abs/1909.03562',
	'arxiv:1909.03562',
	'2019-09-08',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:collatz:formal-conjectures-target',
	'problem-revision:formal-conjectures:collatz:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the exact Collatz declaration and source hash for a local replay. The declaration remains admitted in the catalog and is not a completed formal proof.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/CollatzConjecture.lean#L50',
	'github:google-deepmind/formal-conjectures:collatz',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'CollatzConjecture.collatz_conjecture',
	20
),
(
	'curated:twin-primes:zhang-bounded-gaps',
	'problem-revision:formal-conjectures:twin-primes:main:1',
	'progress',
	'paper',
	'Bounded gaps between primes',
	'Yitang Zhang',
	'Zhang proves a finite unconditional upper bound on the liminf of consecutive prime gaps. Bounded gaps are a major step toward the twin-prime problem, but do not establish infinitely many gaps of exactly two.',
	'Annals of Mathematics',
	'https://annals.math.princeton.edu/2014/179-3/p07',
	'doi:10.4007/annals.2014.179.3.7',
	'2014-05-01',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:twin-primes:maynard-small-gaps',
	'problem-revision:formal-conjectures:twin-primes:main:1',
	'progress',
	'paper',
	'Small gaps between primes',
	'James Maynard',
	'Maynard develops a much smaller unconditional bounded-gap result and a broader bounded-gap framework. This remains distinct from proving the twin-prime conjecture.',
	'Annals of Mathematics',
	'https://annals.math.princeton.edu/2015/181-1/p07',
	'doi:10.4007/annals.2015.181.1.7',
	'2015-01-01',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	20
),
(
	'curated:twin-primes:formal-conjectures-target',
	'problem-revision:formal-conjectures:twin-primes:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the exact infinitude-of-twin-primes declaration and source hash for a local replay. The catalog theorem is admitted and does not claim a proof.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/TwinPrimes.lean#L34-L35',
	'github:google-deepmind/formal-conjectures:twin-primes',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'TwinPrimes.twin_primes',
	30
),
(
	'curated:kakeya:katz-tao-survey',
	'problem-revision:formal-conjectures:kakeya:main:1',
	'progress',
	'review',
	'Recent progress on the Kakeya conjecture',
	'Nets Katz; Terence Tao',
	'This survey records the geometric and harmonic-analytic route through the Wolff and Katz-Tao era of Kakeya progress, giving context for the higher-dimensional target.',
	'arXiv',
	'https://arxiv.org/abs/math/0010069',
	'arxiv:math/0010069',
	'2000-10-07',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:kakeya:wang-zahl-announcement',
	'problem-revision:formal-conjectures:kakeya:main:1',
	'announcement',
	'announcement',
	'Introduction to the proof of the Kakeya conjecture',
	'Larry Guth',
	'A 2025 survey describes the announced Wang-Zahl proof of the three-dimensional Kakeya conjecture. This remains an announcement/review record and is not a Proofweave verification.',
	'arXiv',
	'https://arxiv.org/abs/2505.07695',
	'arxiv:2505.07695',
	'2025-05-12',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	20
),
(
	'curated:kakeya:formal-conjectures-target',
	'problem-revision:formal-conjectures:kakeya:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the general-dimensional Kakeya declaration and source hash for a local replay. The catalog declaration is admitted and does not certify the announced result.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/Kakeya.lean#L59-L60',
	'github:google-deepmind/formal-conjectures:kakeya',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'Kakeya.kakeya_set_conjecture',
	30
),
(
	'curated:lonely-runner:tao-remarks',
	'problem-revision:formal-conjectures:lonely-runner:main:1',
	'progress',
	'paper',
	'Some remarks on the lonely runner conjecture',
	'Terence Tao',
	'Tao improves the basic lower bound for sufficiently large numbers of runners and gives a finite-size reduction. These are quantitative milestones, not a full proof of the conjecture.',
	'arXiv',
	'https://arxiv.org/abs/1701.02048',
	'arxiv:1701.02048',
	'2017-01-09',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:lonely-runner:linearly-exponential-checking',
	'problem-revision:formal-conjectures:lonely-runner:main:1',
	'progress',
	'preprint',
	'Linearly-exponential checking is enough for the Lonely Runner Conjecture and some of its variants',
	'Romanos Diogenes Malikiosis; Francisco Santos; Matthias Schymura',
	'This 2024 result improves the finite-checking bound for the relevant formulation and supplies a bounded computational replay target, rather than a proof of the complete conjecture.',
	'arXiv',
	'https://arxiv.org/abs/2411.06903',
	'arxiv:2411.06903',
	'2024-11-11',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	20
),
(
	'curated:lonely-runner:formal-conjectures-target',
	'problem-revision:formal-conjectures:lonely-runner:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the distinct-speeds formulation and source hash for a local Lean replay. The catalog theorem is admitted and is separate from the finite-checking results above.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/LonelyRunnerConjecture.lean#L36-L42',
	'github:google-deepmind/formal-conjectures:lonely-runner',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'LonelyRunnerConjecture.lonely_runner_conjecture',
	30
),
(
	'curated:navier-stokes:chemin-gallagher-paicu',
	'problem-revision:formal-conjectures:navier-stokes:r3:1',
	'special_case',
	'paper',
	'Global regularity for some classes of large solutions to the Navier-Stokes equations',
	'Jean-Yves Chemin; Isabelle Gallagher; Marius Paicu',
	'This Annals paper establishes global smooth solutions for specified classes of large initial data. It is a partial regularity result, not the full three-dimensional Millennium problem.',
	'Annals of Mathematics',
	'https://annals.math.princeton.edu/2011/173-2/p09',
	'doi:10.4007/annals.2011.173.2.9',
	'2011-03-01',
	'source_asserted',
	NULL,
	NULL,
	NULL,
	10
),
(
	'curated:navier-stokes:formal-conjectures-target',
	'problem-revision:formal-conjectures:navier-stokes:r3:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the whole-space three-dimensional existence-and-smoothness declaration and source hash for a local replay. The declaration is admitted in the catalog and is not a proof.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Millenium/NavierStokes.lean#L266-L268',
	'github:google-deepmind/formal-conjectures:navier-stokes-r3',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'NavierStokes.navier_stokes_existence_and_smoothness_R3',
	20
),
(
	'curated:jacobian:formal-conjectures-target',
	'problem-revision:formal-conjectures:jacobian:main:1',
	'formalization',
	'formalization',
	'Pinned Lean statement in Formal Conjectures',
	'Google DeepMind Formal Conjectures contributors',
	'The pinned snapshot exposes the polynomial inverse statement and source hash for a local Lean replay. The catalog declaration is admitted; this record is a formal target pointer, not a proof claim.',
	'Formal Conjectures',
	'https://github.com/google-deepmind/formal-conjectures/blob/b2e608fc52d765510915a244bb69b1a2741acc3c/FormalConjectures/Wikipedia/JacobianConjecture.lean#L72-L75',
	'github:google-deepmind/formal-conjectures:jacobian',
	'2026-07-16',
	'source_asserted',
	'https://github.com/google-deepmind/formal-conjectures/tree/b2e608fc52d765510915a244bb69b1a2741acc3c',
	'b2e608fc52d765510915a244bb69b1a2741acc3c',
	'JacobianConjecture.jacobian_conjecture',
	10
);
